spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/kk_mall?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456789
  redis:
    database: 0
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 1000
    jedis:
      pool:
        max-wait: -1ms
        min-idle: 5
        max-idle: 10
        max-active: 10



mybatis-plus:
  configuration:
    log-impl: com.kk.mall.common.log.SqlLogImpl